package com.akitflow.notification.domain.enums;

public enum EmailType {
    WELCOME,
    INVITE,
    MEMBER_JOINED,
    CONTRACT_CREATED,
    CONTRACT_STATUS_CHANGED,
    CONTRACT_EXPIRING_SOON,
    CONTRACT_SIGNATURE_REQUESTED,
    CONTRACT_SIGNED,
    CONTRACT_SIGNATURE_REJECTED,
    WORKFLOW_APPROVAL_REQUESTED,
    WORKFLOW_APPROVAL_REJECTED,
    WORKFLOW_APPROVED
}
